language: go

go:
  - "1.11.x"
  - master

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
    - export GO111MODULE=on
    - go mod vendor # goberalls doesn't support go mod yet
    - $GOPATH/bin/goveralls -service=travis-ci
    - make test
