language: go

jobs:
  include:
  - name: UT and Coverage
    stage: test
    script:
    - go get github.com/mattn/goveralls
    - export GO111MODULE=on
    - make test
    - goveralls -coverprofile=coverage.out -service=travis-ci
    go: "1.11.x"
  - name: Lint
    stage: test
    script:
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - export GO111MODULE=on
    - go mod download
    - make lint
    go: "1.11.x"
