language: go

go:
  - "1.x"
  - "1.9"
  - "1.10.x"
  - master

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
    - $GOPATH/bin/goveralls -service=travis-ci
    - make test
